// <auto-generated />
using System;
using ApiPeliculasEFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace ApiPeliculasEFCore.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20221106150458_ProcedimientoAlmacenado")]
    partial class ProcedimientoAlmacenado
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Biografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("FotoURL")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Actores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biografia = "Thomas Stanley Holland (Kingston upon Thames, Londres; 1 de junio de 1996), conocido simplemente como Tom Holland, es un actor, actor de voz y bailarín británico.",
                            FechaNacimiento = new DateTime(1996, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Tom Holland"
                        },
                        new
                        {
                            Id = 2,
                            Biografia = "Samuel Leroy Jackson (Washington D. C., 21 de diciembre de 1948), conocido como Samuel L. Jackson, es un actor y productor de cine, televisión y teatro estadounidense. Ha sido candidato al premio Óscar, a los Globos de Oro y al Premio del Sindicato de Actores, así como ganador de un BAFTA al mejor actor de reparto.",
                            FechaNacimiento = new DateTime(1948, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Samuel L. Jackson"
                        },
                        new
                        {
                            Id = 3,
                            Biografia = "Robert John Downey Jr. (Nueva York, 4 de abril de 1965) es un actor, actor de voz, productor y cantante estadounidense. Inició su carrera como actor a temprana edad apareciendo en varios filmes dirigidos por su padre, Robert Downey Sr., y en su infancia estudió actuación en varias academias de Nueva York.",
                            FechaNacimiento = new DateTime(1965, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Robert Downey Jr."
                        },
                        new
                        {
                            Id = 4,
                            FechaNacimiento = new DateTime(1981, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Chris Evans"
                        },
                        new
                        {
                            Id = 5,
                            FechaNacimiento = new DateTime(1972, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Dwayne Johnson"
                        },
                        new
                        {
                            Id = 6,
                            FechaNacimiento = new DateTime(2000, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Auli'i Cravalho"
                        },
                        new
                        {
                            Id = 7,
                            FechaNacimiento = new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Scarlett Johansson"
                        },
                        new
                        {
                            Id = 8,
                            FechaNacimiento = new DateTime(1964, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Keanu Reeves"
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Cine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Point>("Ubicacion")
                        .HasColumnType("geography");

                    b.HasKey("Id");

                    b.ToTable("Cines");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Nombre = "Acropolis",
                            Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.939248 18.469649)")
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Sambil",
                            Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.911582 18.482455)")
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Megacentro",
                            Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.856309 18.506662)")
                        },
                        new
                        {
                            Id = 1,
                            Nombre = "Agora Mall",
                            Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.9388777 18.4839233)")
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.CineDetalle", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CodigoDeEtica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Historia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Misiones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valores")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cines", (string)null);
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.CineOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CineId")
                        .IsUnique();

                    b.ToTable("CineOfertas");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CineId = 4,
                            FechaFin = new DateTime(2022, 11, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            FechaInicio = new DateTime(2022, 11, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            PorcentajeDescuento = 15m
                        },
                        new
                        {
                            Id = 1,
                            CineId = 1,
                            FechaFin = new DateTime(2022, 11, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            FechaInicio = new DateTime(2022, 11, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            PorcentajeDescuento = 10m
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("EstaBorrado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasFilter("EstaBorrado = 'false'");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstaBorrado = false,
                            Nombre = "Acción"
                        },
                        new
                        {
                            Id = 2,
                            EstaBorrado = false,
                            Nombre = "Animación"
                        },
                        new
                        {
                            Id = 3,
                            EstaBorrado = false,
                            Nombre = "Comedia"
                        },
                        new
                        {
                            Id = 4,
                            EstaBorrado = false,
                            Nombre = "Ciencia ficción"
                        },
                        new
                        {
                            Id = 5,
                            EstaBorrado = false,
                            Nombre = "Drama"
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmisorId")
                        .HasColumnType("int");

                    b.Property<int>("ReceptorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmisorId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("Mensajes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contenido = "Hola, Claudia!",
                            EmisorId = 1,
                            ReceptorId = 2
                        },
                        new
                        {
                            Id = 2,
                            Contenido = "Hola, Felipe, ¿Cómo te va?",
                            EmisorId = 2,
                            ReceptorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Contenido = "Todo bien, ¿Y tú?",
                            EmisorId = 1,
                            ReceptorId = 2
                        },
                        new
                        {
                            Id = 4,
                            Contenido = "Muy bien :)",
                            EmisorId = 2,
                            ReceptorId = 1
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("date");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoPago")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pagos");

                    b.HasDiscriminator<int>("TipoPago");
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("EnCartelera")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEstreno")
                        .HasColumnType("date");

                    b.Property<string>("PosterURL")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnCartelera = false,
                            FechaEstreno = new DateTime(2012, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg",
                            Titulo = "Avengers"
                        },
                        new
                        {
                            Id = 2,
                            EnCartelera = false,
                            FechaEstreno = new DateTime(2017, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg",
                            Titulo = "Coco"
                        },
                        new
                        {
                            Id = 3,
                            EnCartelera = false,
                            FechaEstreno = new DateTime(2021, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg",
                            Titulo = "Spider-Man: No way home"
                        },
                        new
                        {
                            Id = 4,
                            EnCartelera = false,
                            FechaEstreno = new DateTime(2019, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg",
                            Titulo = "Spider-Man: Far From Home"
                        },
                        new
                        {
                            Id = 5,
                            EnCartelera = true,
                            FechaEstreno = new DateTime(2100, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosterURL = "https://upload.wikimedia.org/wikipedia/en/5/50/The_Matrix_Resurrections.jpg",
                            Titulo = "The Matrix Resurrections"
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.PeliculaActor", b =>
                {
                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Personaje")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PeliculaId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("peliculasActores");

                    b.HasData(
                        new
                        {
                            PeliculaId = 4,
                            ActorId = 2,
                            Orden = 2,
                            Personaje = "Samuel L. Jackson"
                        },
                        new
                        {
                            PeliculaId = 4,
                            ActorId = 1,
                            Orden = 1,
                            Personaje = "Peter Parker"
                        },
                        new
                        {
                            PeliculaId = 3,
                            ActorId = 1,
                            Orden = 1,
                            Personaje = "Peter Parker"
                        },
                        new
                        {
                            PeliculaId = 1,
                            ActorId = 3,
                            Orden = 2,
                            Personaje = "Iron Man"
                        },
                        new
                        {
                            PeliculaId = 1,
                            ActorId = 7,
                            Orden = 3,
                            Personaje = "Black Widow"
                        },
                        new
                        {
                            PeliculaId = 1,
                            ActorId = 4,
                            Orden = 1,
                            Personaje = "Capitán América"
                        },
                        new
                        {
                            PeliculaId = 5,
                            ActorId = 8,
                            Orden = 1,
                            Personaje = "Neo"
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Felipe"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Claudia"
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.SalaDeCine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("TipoSalaDeCine")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("DosDimensiones");

                    b.HasKey("Id");

                    b.HasIndex("CineId");

                    b.ToTable("SalaDeCines");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            CineId = 3,
                            Precio = 250m,
                            TipoSalaDeCine = "DosDimensiones"
                        },
                        new
                        {
                            Id = 6,
                            CineId = 3,
                            Precio = 330m,
                            TipoSalaDeCine = "TresDimensiones"
                        },
                        new
                        {
                            Id = 7,
                            CineId = 3,
                            Precio = 450m,
                            TipoSalaDeCine = "CXC"
                        },
                        new
                        {
                            Id = 8,
                            CineId = 4,
                            Precio = 250m,
                            TipoSalaDeCine = "DosDimensiones"
                        },
                        new
                        {
                            Id = 1,
                            CineId = 1,
                            Precio = 220m,
                            TipoSalaDeCine = "DosDimensiones"
                        },
                        new
                        {
                            Id = 2,
                            CineId = 1,
                            Precio = 320m,
                            TipoSalaDeCine = "TresDimensiones"
                        },
                        new
                        {
                            Id = 3,
                            CineId = 2,
                            Precio = 200m,
                            TipoSalaDeCine = "DosDimensiones"
                        },
                        new
                        {
                            Id = 4,
                            CineId = 2,
                            Precio = 290m,
                            TipoSalaDeCine = "TresDimensiones"
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.SinLLave.CineSinUbicacion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.ToView(null);

                    b.ToSqlQuery("Select Id, Nombre FROM Cines");
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.SinLLave.PeliculaConConteos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadActores")
                        .HasColumnType("int");

                    b.Property<int>("CantidadCines")
                        .HasColumnType("int");

                    b.Property<int>("CantidadGeneros")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToSqlQuery("Select Id, Titulo,\r\n(Select count(*)\r\nfrom GeneroPelicula\r\nWHERE PeliculasId = Peliculas.Id) as CantidadGeneros,\r\n(Select count(distinct CineId)\r\nFROM PeliculaSalaDeCine\r\nINNER JOIN SalaDeCines\r\nON SalaDeCines.Id = PeliculaSalaDeCine.SalaDeCineId\r\nWHERE PeliculasId = Peliculas.Id) as CantidadCines,\r\n(\r\nSelect count(*)\r\nFROM PeliculasActores\r\nwhere PeliculaId = Peliculas.Id) as CantidadActores\r\nFROM Peliculas");
                });

            modelBuilder.Entity("GeneroPelicula", b =>
                {
                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("PeliculasId")
                        .HasColumnType("int");

                    b.HasKey("GeneroId", "PeliculasId");

                    b.HasIndex("PeliculasId");

                    b.ToTable("GeneroPelicula");

                    b.HasData(
                        new
                        {
                            GeneroId = 1,
                            PeliculasId = 1
                        },
                        new
                        {
                            GeneroId = 4,
                            PeliculasId = 1
                        },
                        new
                        {
                            GeneroId = 2,
                            PeliculasId = 2
                        },
                        new
                        {
                            GeneroId = 4,
                            PeliculasId = 3
                        },
                        new
                        {
                            GeneroId = 1,
                            PeliculasId = 3
                        },
                        new
                        {
                            GeneroId = 3,
                            PeliculasId = 3
                        },
                        new
                        {
                            GeneroId = 4,
                            PeliculasId = 4
                        },
                        new
                        {
                            GeneroId = 1,
                            PeliculasId = 4
                        },
                        new
                        {
                            GeneroId = 3,
                            PeliculasId = 4
                        },
                        new
                        {
                            GeneroId = 4,
                            PeliculasId = 5
                        },
                        new
                        {
                            GeneroId = 1,
                            PeliculasId = 5
                        },
                        new
                        {
                            GeneroId = 5,
                            PeliculasId = 5
                        });
                });

            modelBuilder.Entity("PeliculaSalaDeCine", b =>
                {
                    b.Property<int>("PeliculasId")
                        .HasColumnType("int");

                    b.Property<int>("SalaDeCineId")
                        .HasColumnType("int");

                    b.HasKey("PeliculasId", "SalaDeCineId");

                    b.HasIndex("SalaDeCineId");

                    b.ToTable("PeliculaSalaDeCine");

                    b.HasData(
                        new
                        {
                            PeliculasId = 5,
                            SalaDeCineId = 3
                        },
                        new
                        {
                            PeliculasId = 5,
                            SalaDeCineId = 4
                        },
                        new
                        {
                            PeliculasId = 5,
                            SalaDeCineId = 1
                        },
                        new
                        {
                            PeliculasId = 5,
                            SalaDeCineId = 2
                        },
                        new
                        {
                            PeliculasId = 5,
                            SalaDeCineId = 5
                        },
                        new
                        {
                            PeliculasId = 5,
                            SalaDeCineId = 6
                        },
                        new
                        {
                            PeliculasId = 5,
                            SalaDeCineId = 7
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Mercancias", b =>
                {
                    b.HasBaseType("ApiPeliculasEFCore.Entidades.Producto");

                    b.Property<bool>("DisponibleEnInventario")
                        .HasColumnType("bit");

                    b.Property<bool>("EsColeccionable")
                        .HasColumnType("bit");

                    b.Property<bool>("EsRopa")
                        .HasColumnType("bit");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<double>("Volumen")
                        .HasColumnType("float");

                    b.ToTable("Mercancias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Nombre = "T-Shirt One Piece",
                            Precio = 11m,
                            DisponibleEnInventario = true,
                            EsColeccionable = false,
                            EsRopa = true,
                            Peso = 1.0,
                            Volumen = 1.0
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.PagoPaypal", b =>
                {
                    b.HasBaseType("ApiPeliculasEFCore.Entidades.Pago");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            FechaTransaccion = new DateTime(2022, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 157m,
                            TipoPago = 1,
                            CorreoElectronico = "Cristian@hotmail.com"
                        },
                        new
                        {
                            Id = 4,
                            FechaTransaccion = new DateTime(2022, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 9.99m,
                            TipoPago = 1,
                            CorreoElectronico = "claudia@hotmail.com"
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.PagoTarjeta", b =>
                {
                    b.HasBaseType("ApiPeliculasEFCore.Entidades.Pago");

                    b.Property<string>("Ultimos4Digitos")
                        .IsRequired()
                        .HasColumnType("char(4)");

                    b.HasDiscriminator().HasValue(2);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaTransaccion = new DateTime(2022, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 500m,
                            TipoPago = 2,
                            Ultimos4Digitos = "0123"
                        },
                        new
                        {
                            Id = 2,
                            FechaTransaccion = new DateTime(2022, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 120m,
                            TipoPago = 2,
                            Ultimos4Digitos = "1234"
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.PeliculaAlquilable", b =>
                {
                    b.HasBaseType("ApiPeliculasEFCore.Entidades.Producto");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.ToTable("PeliculasAlquilables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Spider-Man",
                            Precio = 5.99m,
                            PeliculaId = 1
                        });
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Actor", b =>
                {
                    b.OwnsOne("ApiPeliculasEFCore.Entidades.Direccion", "BillingAddress", b1 =>
                        {
                            b1.Property<int>("ActorId")
                                .HasColumnType("int");

                            b1.Property<string>("Calle")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("barrio")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("casa")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ActorId");

                            b1.ToTable("Actores");

                            b1.WithOwner()
                                .HasForeignKey("ActorId");
                        });

                    b.OwnsOne("ApiPeliculasEFCore.Entidades.Direccion", "DireccionHogar", b1 =>
                        {
                            b1.Property<int>("ActorId")
                                .HasColumnType("int");

                            b1.Property<string>("Calle")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Calle");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("barrio")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Barrio");

                            b1.Property<string>("casa")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Casa");

                            b1.HasKey("ActorId");

                            b1.ToTable("Actores");

                            b1.WithOwner()
                                .HasForeignKey("ActorId");
                        });

                    b.Navigation("BillingAddress");

                    b.Navigation("DireccionHogar");
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Cine", b =>
                {
                    b.OwnsOne("ApiPeliculasEFCore.Entidades.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<int>("CineId")
                                .HasColumnType("int");

                            b1.Property<string>("Calle")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Calle");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("barrio")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("barrio");

                            b1.Property<string>("casa")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("casa");

                            b1.HasKey("CineId");

                            b1.ToTable("Cines");

                            b1.WithOwner()
                                .HasForeignKey("CineId");
                        });

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.CineDetalle", b =>
                {
                    b.HasOne("ApiPeliculasEFCore.Entidades.Cine", "Cine")
                        .WithOne("CineDetalle")
                        .HasForeignKey("ApiPeliculasEFCore.Entidades.CineDetalle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cine");
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.CineOferta", b =>
                {
                    b.HasOne("ApiPeliculasEFCore.Entidades.Cine", null)
                        .WithOne("CineOferta")
                        .HasForeignKey("ApiPeliculasEFCore.Entidades.CineOferta", "CineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Mensaje", b =>
                {
                    b.HasOne("ApiPeliculasEFCore.Entidades.Persona", "Emisor")
                        .WithMany("MensajesEnviados")
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPeliculasEFCore.Entidades.Persona", "Receptor")
                        .WithMany("MensajesRecibidos")
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emisor");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.PeliculaActor", b =>
                {
                    b.HasOne("ApiPeliculasEFCore.Entidades.Actor", "Actor")
                        .WithMany("PeliculaActores")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPeliculasEFCore.Entidades.Pelicula", "Pelicula")
                        .WithMany("PeliculaActores")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.SalaDeCine", b =>
                {
                    b.HasOne("ApiPeliculasEFCore.Entidades.Cine", "Cine")
                        .WithMany("SalaDeCines")
                        .HasForeignKey("CineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cine");
                });

            modelBuilder.Entity("GeneroPelicula", b =>
                {
                    b.HasOne("ApiPeliculasEFCore.Entidades.Genero", null)
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPeliculasEFCore.Entidades.Pelicula", null)
                        .WithMany()
                        .HasForeignKey("PeliculasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeliculaSalaDeCine", b =>
                {
                    b.HasOne("ApiPeliculasEFCore.Entidades.Pelicula", null)
                        .WithMany()
                        .HasForeignKey("PeliculasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPeliculasEFCore.Entidades.SalaDeCine", null)
                        .WithMany()
                        .HasForeignKey("SalaDeCineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Mercancias", b =>
                {
                    b.HasOne("ApiPeliculasEFCore.Entidades.Producto", null)
                        .WithOne()
                        .HasForeignKey("ApiPeliculasEFCore.Entidades.Mercancias", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.PeliculaAlquilable", b =>
                {
                    b.HasOne("ApiPeliculasEFCore.Entidades.Producto", null)
                        .WithOne()
                        .HasForeignKey("ApiPeliculasEFCore.Entidades.PeliculaAlquilable", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Actor", b =>
                {
                    b.Navigation("PeliculaActores");
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Cine", b =>
                {
                    b.Navigation("CineDetalle");

                    b.Navigation("CineOferta");

                    b.Navigation("SalaDeCines");
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Pelicula", b =>
                {
                    b.Navigation("PeliculaActores");
                });

            modelBuilder.Entity("ApiPeliculasEFCore.Entidades.Persona", b =>
                {
                    b.Navigation("MensajesEnviados");

                    b.Navigation("MensajesRecibidos");
                });
#pragma warning restore 612, 618
        }
    }
}
